name: Code Check

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean dependencies
        run: ./gradlew clean androidDependencies

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Check code formatting
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew test
