name: Code Check

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean dependencies
        run: ./gradlew clean androidDependencies

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Check code formatting
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport

      - name: Add branch coverage report to PR
        id: koverBranchHealthCompanion
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/app/build/reports/kover/report.xml
          title: Code Coverage Branch
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: BRANCH

      - name: Add line coverage report to PR
        id: koverLineHealthCompanion
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/app/build/reports/kover/report.xml
          title: Code Coverage Line
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE
